// resource.h - Resource identifier constants generated by Visual Studio.
// Defines IDs for the main icon, menus, dialogs, string table entries,
// and control commands used throughout the application.
//
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ergo-active.rc
//
#define ID_EXIT                         3
#define IDR_MAINFRAME                   128
#define IDS_BREAK                       130
#define IDR_MENU1                       202
#define IDD_EXIT                        203
#define IDC_ST_RESTORE                  32771
#define ID_APP_EXIT                     32772
#define ID_TESTBUBBLE                   32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
